language: python
python:
  - "3.7.4"
cache: pip
# command to install dependencies
install:
  - pip3 install -r requeriments.txt
# command to run tests
script:
  - coverage run --source='.' ./manage.py test 
after_success:
  - coveralls
